version: "2"
services:
  nginx:
    image: nginx

    volumes:
      - ./docker/nginx/app.nginx:/etc/nginx/conf.d/default.conf

    ports:
      - 8080:80

  www:
    build: .

    volumes:
      - .:/app

    environment:
      NODE_ENV: development
      NODE_PORT: 80
